### ISSUE TITLE
Transfer todo list to GH issues

### ISSUE THREAD

**Issue by bishax** [nestauk/sg_covid_impact#32]
https://docs.google.com/spreadsheets/d/1OLrJTeS7w279nGYSobUbEGDCr4ADreTq291VrHdfDuU/edit#gid=1386834576

**Comment by SeanyKC** [comment]
@bishax Do we want completed actions as well as open ones so we have a full record or is that a bit of over kill?

**Comment by bishax** [comment]
Overkill I think. The link is there for posterity.
