### ISSUE TITLE
Error when installing environment

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/sg_covid_impact#49]
When running `conda env update --file conda_environment.yaml` I get:

```
Solving environment: failed

ResolvePackageNotFound:
  - gcc_linux-64
```

**Comment by bishax** [comment]
**Solution:** Run `make update_environment` instead 

**Explanation:**
It runs the code snippet below instead, which filters out packages annotated with `# [not linux]` (if not on linux) or   `# [not darwin]` (if not on OSX - which OSX calls itself at the system level?). It's not pretty but it's necessary to work around conda's inability to specify cross-platform environments (and why I want cookiecutter-v2 to have the option to run in a docker container, abstracting as much Docker as possible away from the user).  

```
cat conda_environment.yaml | grep "\[not .*$(shell python -c 'import sys; print(sys.platform)').*\]" -v > /tmp/environment.yaml
conda env update -f /tmp/environment.yaml
```

Source: https://github.com/nestauk/sg_covid_impact/blob/b17c61e5f163c8ae36059222b89466bd8140bb91/Makefile#L85
